function placePhoto(p){const photo=p.photo;return photo?'<figure class="place-photo"><img src="'+esc(photo.src)+'" alt="'+esc(photo.alt)+'" loading="lazy" decoding="async" width="640" height="360"><figcaption>'+external(photo.source,photo.credit||'תמונה מאתר המקום')+'</figcaption></figure>':''}
const $=s=>document.querySelector(s), main=$('#main');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const hotel='Hotel Hubert Pod Poliankou 302 Gerlachov Slovakia';
const lookup=id=>PLACES.find(p=>p.id===id);
const external=(url,label)=>`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`;
function maps(dest,origin){return 'https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(dest)+(origin?'&origin='+encodeURIComponent(origin):'')+'&travelmode=driving'}
const waze=q=>'https://waze.com/ul?q='+encodeURIComponent(q)+'&utm_source=tatry_family';
const pin=p=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(p.map);
let visited={};
let remainingOnly=true;
let day=0,view='days',query='',kind='all';let checked={};
function storeChecks(){}
function changeView(v){view=v;document.querySelectorAll('.mainnav button').forEach(b=>{b.classList.toggle('selected',b.dataset.view===v);b.setAttribute('aria-current',b.dataset.view===v?'page':'false')});render();}

function kidsBlock(p){return p.kids?'<details class="kids"><summary><span class="kids-tag">ליובל ולאיתי</span> מה מחכה לנו כאן?</summary><p>'+esc(p.kids[0])+'</p><p class="discovery"><b>משימת גילוי</b> '+esc(p.kids[1])+'</p></details>':''}
function visitItems(p){return p.activities||[[p.id,p.name]]}
function visitChecks(p){return '<div class="visitchecks">'+visitItems(p).map(([id,label])=>'<label class="visit '+(visited[id]?'done':'')+'"><input type="checkbox" data-visit="'+esc(id)+'" '+(visited[id]?'checked':'')+'><span>'+esc(label)+' <small>· עשינו</small></span></label>').join('')+'</div>'}
function bookingNote(p){return p.booking?'<div class="booking"><strong>'+esc(p.booking.level)+'</strong><p>'+esc(p.booking.text)+'</p></div>':''}
function quickLinks(p){return '<div class="actions">'+external(p.url,'פרטי הפעילות')+(p.ticket?external(p.ticket.url,p.ticket.label):'')+(p.links||[]).map(([label,url])=>external(url,label)).join('')+(p.parking?external(maps(p.parking.query),'חניה במפה')+external(waze(p.parking.query),'חיפוש חניה ב־Waze'):external(waze(p.map),'חיפוש ב־Waze'))+'<button class="softbutton" data-copy-destination="'+esc(p.parking?.query||p.map)+'">העתקת יעד</button></div><div class="place-tools"><button data-tool-view="files" data-tool-place="'+p.id+'">▱ כרטיסים למקום</button><button data-tool-view="budget" data-tool-place="'+p.id+'">＋ הוצאה כאן</button></div>'}
function logistics(p){return bookingNote(p)+(p.ticket?'<p class="source">'+esc(p.ticket.note)+'</p>':'')+(p.parking?'<details class="parking"><summary>חניה · '+esc(p.parking.name)+'</summary><p>'+esc(p.parking.price)+'</p><p class="source">'+esc(p.parking.note)+'</p><div class="actions">'+external(maps(p.parking.query),'ניווט לחניה')+external(p.parking.source,'מקור לפרטי החניה')+'</div><p class="source">המחירים שנבדקו הם לרכב פרטי, לפי המידע הזמין בספטמבר 2026; לא התחייבות לאוגוסט 2027. זמינות מקום וחניה חוקית לפי השילוט.</p></details>':'')}
function visitsView(){const entries=new Map();PRESENT_PLACES().forEach(p=>visitItems(p).forEach(([id,label])=>{if(!entries.has(id))entries.set(id,{id,label,p})}));const all=[...entries.values()],done=all.filter(x=>visited[x.id]).length;main.innerHTML='<h2>החוויות שלנו · מה עוד נשאר?</h2><p class="muted">כל פעילות מסומנת בנפרד. סימון מתעדכן בכל מקום שבו היא חוזרת במסלול. האפשרויות הן לבחירה — אין צורך להשלים הכול.</p><div class="note">'+done+' חוויות סומנו · '+(all.length-done)+' עדיין לא סומנו</div><label class="check"><input type="checkbox" id="remaining-only" '+(remainingOnly?'checked':'')+'> להציג רק מה שעוד לא עשינו</label><p class="source">לאחר התחברות הסימונים משותפים למשתמשים שאושרו לטיול. אפשר לשנות כל סימון.</p><div class="cards">'+all.filter(x=>!remainingOnly||!visited[x.id]).map(x=>'<article class="card"><span class="pill">'+esc(x.p.area)+'</span>'+visitChecks({...x.p,activities:[[x.id,x.label]]})+'<button class="softbutton" data-place="'+x.p.id+'">פרטים וקישורים</button></article>').join('')+'</div>';}
function PRESENT_PLACES(){return PLACES.filter(p=>DAYS.some(d=>d.stops.some(s=>s[3]===p.id)||d.options?.some(o=>o[2]===p.id)))}
function bookingsView(){main.innerHTML='<h2>הזמנות ובירורים מראש</h2><div class="note">לא מזמינים עכשיו כרטיסים מוגבלי תוקף לאוגוסט 2027. תזמון שמוגדר כהמלצה הוא תכנון שלנו; דרישה רשמית מסומנת במפורש.</div><div class="cards">'+PLACES.filter(p=>p.booking).map(p=>'<article class="card"><h3>'+esc(p.name)+'</h3>'+bookingNote(p)+quickLinks(p)+'</article>').join('')+'</div>';}
function roadStops(){return '<section class="roadstops"><h3>מקרקוב: שתי עצירות לבחירה</h3><p>למסלול דרך S7 ו־Nowy Targ: קודם משחק ב־Rabka, ואחר כך גלידה ב־Nowy Targ. בחרו אחת כברירת מחדל. שתיהן יחד מוסיפות בערך 1:45–2:50 שעות כולל סטיות, מעבר לנסיעה הישירה; לכן אין להסתמך על תקציב 3–4 שעות לשתי עצירות. בנחיתה מאוחרת מדלגים.</p><div class="options">'+['rabka','krzywa'].map(id=>{const p=lookup(id);return '<article class="option"><h4>'+esc(p.name)+'</h4><p>'+esc(p.desc)+'</p><p class="source">'+esc(p.duration)+' · '+esc(p.drive)+'</p>'+dayPlaceDetails(p)+'</article>'}).join('')+'</div><div class="actions">'+external(maps(hotel,'Krakow Airport KRK')+'&waypoints='+encodeURIComponent('Park Zdrojowy Rabka Zdroj|Krzywa 16 Nowy Targ'),'ניווט עם שתי העצירות')+'</div></section>';}

function placeCard(p){return `<article class="card" id="place-${p.id}">${placePhoto(p)}<span class="pill">${esc(p.area)}</span><span class="pill">${esc(p.type)}</span><h3><bdi>${esc(p.name)}</bdi></h3><p>${esc(p.desc)}</p>${kidsBlock(p)}<dl class="facts"><dt>שעות פתיחה</dt><dd>${esc(p.hours)}</dd><dt>זמן ביקור</dt><dd>${esc(p.duration)}</dd><dt>הגעה</dt><dd>${esc(p.drive)}</dd><dt>מאמץ</dt><dd>${esc(p.effort)}</dd><dt>מחיר</dt><dd>${esc(p.price)}</dd></dl><p class="status">${esc(p.status)}</p>${visitChecks(p)}${logistics(p)}${quickLinks(p)}<div class="actions">${external(p.url,'מקור ופרטי פתיחה')}${p.extra?external(p.extra,'מקור נוסף'):''}${external(pin(p),'מיקום במפה')}</div></article>`}
let dayPlaces=new Set();
function dayPlaceDetails(p){if(!p)return '';const anchor='day-place-'+p.id;if(dayPlaces.has(p.id))return '<a class="repeat-place" href="#'+anchor+'">↥ הפעילויות, הסימונים והקישורים של '+esc(p.name)+' מופיעים למעלה</a>';dayPlaces.add(p.id);return '<div id="'+anchor+'" class="day-place-details">'+placePhoto(p)+kidsBlock(p)+visitChecks(p)+bookingNote(p)+quickLinks(p)+'<button class="softbutton" data-place="'+p.id+'">שעות, מחיר ופרטים</button></div>'}
function dayView(){const d=DAYS[day];dayPlaces=new Set();main.innerHTML=`<div class="tripgrid"><nav class="daynav" aria-label="ימי הטיול">${DAYS.map((x,i)=>`<button data-day="${i}" class="${day===i?'selected':''}" ${day===i?'aria-current="date"':''}><strong>${x.date}</strong><span>${esc(x.short)}<small>${x.weekday} · אוגוסט</small></span></button>`).join('')}</nav><section><div class="dayhead"><div><span class="daystamp">${d.date}<small>AUG</small></span><p class="eyebrow">${d.weekday} · ${d.date}.08.2027 / יום ${day+1} מתוך 10</p><h2>${esc(d.title)}</h2><span class="pill">${esc(d.mood)}</span><span class="pill">${esc(d.weather)}</span></div><button class="softbutton" data-action="print">הדפסת היום</button></div><div id="day-hub"></div><div id="day-routes"></div><p class="muted">${esc(d.route)}</p><div class="note">${esc(d.note)}</div><div class="actions"><button class="softbutton" data-view="bookings">חשוב: הזמנות מראש</button><button class="softbutton" data-view="visits">מה עוד לא עשינו?</button></div>${(day===0||day===9)?airportBlock(day===9):''}<p class="counter">השעות בציר היום הן הצעת תכנון · שעות הפתיחה מופיעות בכל מקום</p><div class="timeline">${d.stops.map(s=>{const p=lookup(s[3]);return `<article class="stop"><div class="time">${esc(s[0])}</div><div class="stopbody"><h3>${esc(s[1])}</h3><p>${esc(s[2])}</p>${dayPlaceDetails(p)}</div></article>`}).join('')}</div>${d.options?.length?`<section class="optional"><h3>עוד משהו ליובל ולאיתי?</h3><p class="muted">אפשרויות לבחירה, במקום פעילות אחרת או אם נשאר זמן.</p><div class="options">${d.options.map(o=>`<div class="option"><b>${esc(o[0])}</b><p>${esc(o[1])}</p>${dayPlaceDetails(lookup(o[2]))}</div>`).join('')}</div></section>`:''}<details><summary>ניווט, הגעה ותכנית לגשם</summary><p><b>פותחים Waze מהארץ?</b> הקישור מציג חיפוש יעד. בחרו את החניה הנכונה לפני התחלת ניווט. אם מתקבלת שגיאה, נסו להעתיק את היעד לחיפוש בתוך האפליקציה או פתחו את הקישור למפת Google. המסלול מישראל אינו מדד לזמן הנסיעה בטיול.</p><p>כל זמני הנסיעה הם אומדני תכנון ואינם בדיקת תנועה חיה. הוסיפו 15–30 דקות לחניה, התארגנות והליכה לתחנות, ובימים עמוסים יותר. ניווט למפלים או לפסגה אינו הוראת הגעה ברכב: מתחילים בחניה ובתחנת הרכבל המתאימות.</p><p>בגשם: FunVille או Poliankovo; בריכות לפי פעילות המתקנים. Fantázia רק לאחר אישור פתיחה. יום פסגה או Bachledka אפשר להעביר ליום הגמיש בכפוף לכרטיסים.</p><div class="actions">${d.driveTo?external(maps(d.driveTo,hotel),'מסלול נסיעה מהמלון'):external(pin(lookup('hotel')),'מיקום המלון')}${external('https://www.vt.sk/en/info/info/cableways-opening-hours','מצב רכבלים')}</div></details></section></div>`;if(typeof DayHub!=='undefined')DayHub.mount();if(typeof DayRoutes!=='undefined')DayRoutes.mount();}
function airportBlock(back){return `<div class="airport"><h3>${back?'חזרה: שני שדות אפשריים':'נחיתה: שני שדות אפשריים'}</h3><div class="options"><div class="option"><b>Poprad-Tatry · TAT</b><p>15–25 דק׳ נסיעה משוערות ${back?'מהמלון':'למלון'}, לפני החזרת/איסוף הרכב וזמן הטרמינל.</p>${external(maps(back?'Poprad Tatry Airport':hotel,back?hotel:'Poprad Tatry Airport'),'מסלול TAT')}${external(waze(back?'Poprad Tatry Airport':hotel),'חיפוש ב־Waze')}</div><div class="option"><b>Kraków-Balice · KRK</b><p>להקצות כ־3–4 שעות לכביש ולהפסקה משפחתית כמרווח תכנון, לפני זמני שדה התעופה והשכרת הרכב. זה אינו זמן נסיעה חי שנמדד.</p><p>${back?'בטיסת בוקר מוקדמת: לשקול לילה אחרון ליד השדה; זה משנה את הלילה התשיעי במלון. לא לשלב אטרקציה לפני הטיסה.':'ביום נחיתה מאוחר: הגעה, אוכל ושינה. לא להזמין אטרקציה לאותו יום.'}</p>${external(maps(back?'Krakow Airport KRK':hotel,back?hotel:'Krakow Airport KRK'),'מסלול KRK')}${external(waze(back?'Krakow Airport KRK':hotel),'חיפוש ב־Waze')}</div></div>${back?'':roadStops()}<p class="source">לוודא שחברת ההשכרה מאשרת מעבר בין פולין לסלובקיה וכיסוי מתאים. שעה מדויקת נקבעת לאחר הזמנת הטיסות; אין כאן הבטחה לטיסה ישירה.</p></div>`}
function placesView(){main.innerHTML=`<h2>כל מקום, עם הפרטים שצריך</h2><p class="muted">מקורות, שעות, מאמץ וקישורי מפה. בדיקה ב־15.09.2026; לוחות הקיץ הבא דורשים רענון.</p><div class="filterbar"><input id="search" type="search" placeholder="חפשו מקום, אזור או שוקולד…" aria-label="חיפוש מקומות" value="${esc(query)}"><select id="kind" aria-label="סוג בילוי"><option value="all">כל המקומות</option>${['מקורה','חוץ','משולב','אוכל'].map(x=>`<option ${kind===x?'selected':''}>${x}</option>`).join('')}</select></div><p id="count" class="counter" aria-live="polite"></p><div id="results" class="cards"></div>`;updateResults();$('#search').addEventListener('input',e=>{query=e.target.value;updateResults()});$('#kind').addEventListener('change',e=>{kind=e.target.value;updateResults()})}
function updateResults(){const items=PLACES.filter(p=>(kind==='all'||p.type===kind)&&[p.name,p.area,p.desc,window.TripI18n?.english([p.name,p.area,p.desc].join(' '))||''].join(' ').toLowerCase().includes(query.toLowerCase()));$('#results').innerHTML=items.length?items.map(placeCard).join(''):'<p class="empty">לא נמצאו מקומות. נסו שם אחר או את כל סוגי הבילוי.</p>';$('#count').textContent=items.length+' מקומות';}
function prepView(){let i=0;const total=PREP.reduce((n,g)=>n+g.length-1,0),done=Array.from({length:total},(_,i)=>checked[i]).filter(Boolean).length;main.innerHTML=`<h2>לפני שיוצאים להרים</h2><p>יובל בן 5 · איתי בן 7 · עומרי וליאת</p><p id="progresslabel" class="counter" aria-live="polite">${done} מתוך ${total} בוצעו</p><div class="progress"><i style="width:${100*done/total}%"></i></div><p class="source muted">לאחר התחברות הסימונים מסתנכרנים לטיול המשפחתי.</p>${PREP.map(g=>`<section class="card prepgroup"><h3>${esc(g[0])}</h3>${g.slice(1).map(t=>{const k=i++;return `<label class="check"><input type="checkbox" data-check="${k}" ${checked[k]?'checked':''}><span>${esc(t)}</span></label>`}).join('')}</section>`).join('')}<div class="note">לא משאירים את יובל ואיתי ללא השגחה. בילויי המים בתכנית הם יחד עם ההורים; ספא זוגי בזמן שהילדים ״משחקים ליד״ הוסר.</div>${airportBlock(false)}<div class="actions">${external('https://www.gopass.travel/','Gopass')}${external('https://www.tatry.sk/tatrycard/en/','TATRY Card')}${external('https://www.hotel-hubert.sk/','המלון')}</div>`;}
function auditView(){main.innerHTML=`<h2>מה השתנה, ועל מה זה מבוסס</h2><p class="muted">נבדק ב־15.09.2026. כל תיקון מקושר למקור; המלצות סדר היום ומרווחי הזמן הן שיקול תכנוני.</p><div class="card">${AUDIT.map(a=>`<div class="auditrow"><b>${esc(a[0])}</b><div>${esc(a[1])}${a[2]?`<p class="source">${external(a[2],'מקור')}</p>`:''}</div></div>`).join('')}</div>`}
function render(){if(view==='map')TripMap.show();else if(view==='days')dayView();else if(view==='places')placesView();else if(view==='prep')prepView();else if(view==='visits')visitsView();else if(view==='bookings')bookingsView();else if(view==='offline')offlineView();else if(view==='files')TripTools.filesView();else if(view==='budget')TripTools.budgetView();else auditView()}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view)changeView(b.dataset.view);if(b.dataset.day!==undefined){day=Number(b.dataset.day);dayView()}if(b.dataset.place){query=lookup(b.dataset.place).name;kind='all';changeView('places');main.scrollIntoView({block:'start'});}if(b.dataset.action==='print')window.print()});
document.addEventListener('change',e=>{if(e.target.matches('[data-visit]')){if(!FamilySync.active){e.target.checked=false;return}const id=e.target.dataset.visit;visited[id]=e.target.checked;document.querySelectorAll('[data-visit]').forEach(el=>{if(el.dataset.visit===id){el.checked=visited[id];el.closest('label').classList.toggle('done',visited[id])}});if(view==='visits')visitsView();return;}if(e.target.id==='remaining-only'){remainingOnly=e.target.checked;visitsView();return;}if(e.target.matches('[data-check]')){if(!FamilySync.active){e.target.checked=false;return}checked[e.target.dataset.check]=e.target.checked;storeChecks();const total=PREP.reduce((n,g)=>n+g.length-1,0),done=Array.from({length:total},(_,i)=>checked[i]).filter(Boolean).length;$('#progresslabel').textContent=done+' מתוך '+total+' בוצעו';$('.progress i').style.width=100*done/total+'%'}});
$('#credit').innerHTML='צילום Štrbské pleso: '+external('https://commons.wikimedia.org/wiki/File:Strbske_pleso_panorama_137.jpg','Rafał Kozubek / Wikimedia Commons')+' · '+external('https://creativecommons.org/licenses/by-sa/4.0/','CC BY-SA 4.0')+' · הוקטן ונחתך לתצוגה.';
render();
// Private wallet is opened only after approved membership has been checked.
const daysLeft=Math.ceil((new Date('2027-08-09T00:00:00+02:00')-new Date())/86400000);$('#countdown').textContent=daysLeft>0?'עוד '+daysLeft+' ימים':'הטיול שלנו';

document.addEventListener('click',async e=>{const b=e.target.closest('[data-copy-destination]');if(!b)return;const text=b.dataset.copyDestination;try{await navigator.clipboard.writeText(text);b.textContent='היעד הועתק ✓';setTimeout(()=>b.textContent='העתקת יעד',2500)}catch{window.prompt('העתיקו את היעד לחיפוש ב־Waze או במפות:',text)}});


window.addEventListener('tatry-private-state',e=>{visited=e.detail.visited;checked=e.detail.checked;document.querySelectorAll('[data-visit]').forEach(el=>{el.checked=!!visited[el.dataset.visit];el.closest('label')?.classList.toggle('done',el.checked)});document.querySelectorAll('[data-check]').forEach(el=>el.checked=!!checked[el.dataset.check]);if(['visits','prep'].includes(view))render()});
