/* Day overview and private booking records, using the existing family wallet. */
const DayHub=(()=>{
 let selected='',lastDay=-1,message='',saving=false;
 const status={needed:'צריך להזמין',booked:'הוזמן',none:'לא נדרשת הזמנה'};
 const shortPlans=['ביום הנחיתה מספיקים הגעה, ארוחה ומנוחה. עצירת דרך אחת היא בונוס.','אפשר להסתפק ב־Hrebienok בלי להמשיך למפלים. בגשם בוחרים ב־Tricklandia.','שביל הצמרות הוא העיקר. בוחרים תוספות לפי הכוח; ברוח או בגשם מעבירים ליום הגמיש.','אין חובה להשלים הקפה סביב האגם. המגדל ו־Orlíkovo הם תוספות לבחירה.','הפסגה תלויה ברוח ובראות. השאירו זמן לירידה האחרונה לפי לוח המפעיל.','מגלשת ההרים היא העוגן. בעייפות מסתפקים במגלשה ובארוחה, בלי כל התוספות.','בריכות עם הפסקות. משחקייה או קינוח יכולים להחליף פעילות, לא חייבים להתווסף.','בוחרים פעילות מרכזית אחת שלא הספקתם. הרשימה אינה תכנית לבצע הכול.','חוזרים לפעילות אהובה ומשאירים זמן לאריזה.','מועד היציאה נקבע לפי הטיסה והשדה. מדלגים על בונוסים שמצמצמים את מרווח ההגעה.'];
 const gear=['מים, נשנוש ובגדים להחלפה','הכרטיסים הורדו לקבצים ונבדקו במצב טיסה','בדקנו תחזית, פתיחה וירידה אחרונה','בחרנו חניה ויעד לניווט'];
 const done=p=>visitItems(p).every(([id])=>visited[id]);
 function mount(force=false){const host=document.querySelector('#day-hub');if(!host||view!=='days')return;if(!force&&host.contains(document.activeElement)&&document.activeElement?.closest('form'))return;
 const d=DAYS[day],required=[...new Set(d.stops.map(s=>s[3]))].map(lookup).filter(Boolean),all=[...new Set([...d.stops.map(s=>s[3]),...(d.options||[]).map(o=>o[2])])].map(lookup).filter(Boolean);
 if(lastDay!==day){lastDay=day;selected=(required.find(p=>p.id!=='hotel'&&!done(p))||required[0])?.id;message=''}const p=lookup(selected);if(!p)return;
 const ready=TripTools.isReady(),b=TripTools.getReservations().find(b=>b.place===p.id),count=required.filter(done).length;
 host.innerHTML=`<section class="day-hub"><header class="hub-top"><div><p class="eyebrow">היום שלנו · ${d.date} באוגוסט</p><h3>פחות לחפש. יותר לטייל.</h3><p>${esc(shortPlans[day])}</p></div><div class="hub-progress"><strong>${count}<small> / ${required.length}</small></strong><span>מקומות שסומנו</span></div></header><div class="hub-body"><section class="hub-next"><label>לאן עכשיו?<select id="hub-place">${all.map(x=>`<option value="${x.id}" ${x.id===p.id?'selected':''}>${esc(x.name)}${done(x)?' · עשינו ✓':''}</option>`).join('')}</select></label><p class="source">בחרו עצירה. ההצעה מבוססת על סדר המסלול והסימונים, ללא מעקב מיקום.</p><div class="hub-facts"><p><small>משך הפעילות</small><b>${esc(p.duration)}</b></p><p><small>מה מצפה לרגליים?</small><b>${esc(p.effort)}</b></p></div><div class="actions">${external(waze(p.parking?.query||p.map),p.parking?'ניווט לחניה':'חיפוש יעד ב־Waze')}${p.ticket?external(p.ticket.url,p.ticket.label):''}<button class="softbutton" data-tool-view="files" data-tool-place="${p.id}">הכרטיסים שלנו${ready?' · '+TripTools.fileCount(p.id):''}</button><button class="softbutton" data-place="${p.id}">פרטים ותמונות</button></div>${p.parking?`<p class="source">${esc(p.parking.name)} · ${esc(p.parking.price)}</p>`:''}</section><section class="hub-booking"><p class="eyebrow">ההזמנה שלנו · פרטי למשפחה</p>${bookingNote(p)}${ready?`<form id="reservation-form"><input type="hidden" name="place" value="${p.id}"><label>מצב<select name="status">${Object.entries(status).map(([v,n])=>`<option value="${v}" ${(b?.status||'needed')===v?'selected':''}>${n}</option>`).join('')}</select></label><div class="form-pair"><label>תאריך<input name="date" type="date" value="${esc(b?.date||'')}"></label><label>שעה מקומית<input name="time" type="time" value="${esc(b?.time||'')}"></label></div><label>מספר הזמנה · רשות<input name="reference" maxlength="120" autocomplete="off" value="${esc(b?.reference||'')}"></label><button class="primarybutton" ${saving?'disabled':''}>שמירת פרטי ההזמנה</button></form>${b?TripTools.itemStatus('check','reservation:'+p.id):'<p class="source">טרם נשמר מעקב למקום הזה. הסימון אינו מבצע רכישה.</p>'}`:'<p>התחברו בחלונית הסנכרון כדי לשמור תאריך, שעה ומספר הזמנה ולשתף עם המשפחה.</p>'}<p id="reservation-message" role="status">${esc(message)}</p></section></div><details class="hub-ready"><summary>לפני שיוצאים · ארבע בדיקות קטנות</summary><div class="hub-checks">${gear.map((label,i)=>{const id='ready:'+day+':'+i;return `<label><input type="checkbox" data-ready="${id}" ${checked[id]?'checked':''} ${ready?'':'disabled'}>${label}</label>`}).join('')}</div><p class="source">סימון ידני לכל יום, מסונכרן למשפחה לאחר התחברות. אינו בודק אוטומטית קבצים או מזג אוויר. בגשם אפשר לשקול FunVille או Poliankovo לפי פתיחה ומיקום.</p></details></section>`;TripTools.paintSaveStatus();}
 document.addEventListener('change',async e=>{if(e.target.id==='hub-place'){selected=e.target.value;message='';mount(true)}if(e.target.matches('[data-ready]')){const el=e.target,key=el.dataset.ready,old=!!checked[key];el.disabled=true;try{if(!TripTools.isReady())throw Error('התחברו כדי לשמור');await TripTools.mark('check',key,el.checked);checked[key]=el.checked}catch(err){el.checked=old;document.querySelector('#reservation-message').textContent=err.message}finally{el.disabled=!TripTools.isReady()}}});
 document.addEventListener('submit',async e=>{if(e.target.id!=='reservation-form')return;e.preventDefault();if(saving)return;saving=true;const form=e.target,button=form.querySelector('button');button.disabled=true;try{await TripTools.saveReservation(Object.fromEntries(new FormData(form)));message='נשמר. מצב הסנכרון מופיע מעל הודעה זו.';saving=false;if(document.contains(form))mount(true)}catch(err){if(document.contains(form))document.querySelector('#reservation-message').textContent=err.message}finally{saving=false;button.disabled=false}});
 for(const event of ['tatry-private-state','tatry-tools-updated','tatry-db-ready'])window.addEventListener(event,()=>mount(!TripTools.isReady()));mount();return {mount};
})();
