(()=>{
 const panel=document.createElement('section');panel.className='family-panel';panel.setAttribute('aria-label','סנכרון משפחתי');panel.innerHTML='<details><summary>🔒 התיק המשפחתי <span id="family-status" role="status">כניסה וסנכרון</span></summary><div id="family-controls"></div></details>';
 document.querySelector('#trip-overview').after(panel);let current='',state={};
 const safe=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function draw(s){state=s;document.querySelector('#family-status').textContent=s.message;const key=JSON.stringify([s.email,s.trip,s.active]);if(key===current)return;current=key;
  document.querySelector('#family-controls').innerHTML=!s.email?`<p>הכרטיסים, ההוצאות והסימונים משותפים רק לחשבונות שאושרו לטיול.</p><form id="family-login"><label>כתובת אימייל<input name="email" type="email" autocomplete="email" required dir="ltr"></label><button class="primarybutton">שליחת קישור כניסה</button></form>`:
   `<p>מחובר/ת: <bdi>${safe(s.email)}</bdi></p>`+(s.active?`<p>${safe(s.trip.name)} · קוד הצטרפות: <bdi><strong>${safe(s.trip.join_code)}</strong></bdi></p><p class="source">הקוד עובד רק עבור אימייל שאושר מראש. קבצים שכבר הורדתם למכשיר נשארים בשליטתכם.</p><div class="actions"><button class="softbutton" data-family="sync">סנכרון עכשיו</button><button class="softbutton" data-family="import">העברת הנתונים הישנים ממכשיר זה</button></div>`:`<p>יצירת טיול והצטרפות זמינות רק לחשבונות שאושרו במסד הנתונים.</p><button class="softbutton" data-family="create">יצירת הטיול שלנו</button><form id="family-join"><label>קוד הצטרפות<input name="code" required minlength="8" maxlength="8" dir="ltr"></label><button class="softbutton">הצטרפות</button></form>`)+`<button class="textbutton" data-family="out">יציאה וניקוי העותק הפרטי במכשיר</button>`;
 }
 window.addEventListener('tatry-sync-status',e=>draw(e.detail));
 const cooldownKey='tatry-email-next-at';let sending=false,nextAt=0;
 try{nextAt=Number(localStorage.getItem(cooldownKey))||0}catch{}
 function loginButton(){const button=document.querySelector('#family-login button');if(!button)return;const seconds=Math.max(0,Math.ceil((nextAt-Date.now())/1000));button.disabled=sending||seconds>0;button.textContent=sending?'שולח קישור…':seconds?'שליחה נוספת בעוד '+seconds+' שניות':'שליחת קישור כניסה'}
 function cooldown(){nextAt=Date.now()+60000;try{localStorage.setItem(cooldownKey,String(nextAt))}catch{}loginButton()}
 function errorMessage(e){return e?.status===429||/rate.?limit|too many requests/i.test(e?.message||'')?'שירות המייל הגיע למגבלת השליחה. המתינו לחידוש המכסה לפני ניסיון נוסף. לחיצות חוזרות לא יפתרו זאת. לשימוש קבוע צריך להגדיר ספק דואר (SMTP) ב־Supabase.':'לא הושלם: '+(e?.message||'אירעה שגיאה')}
 async function action(fn){try{await fn()}catch(e){document.querySelector('#family-status').textContent=errorMessage(e)}}
 document.addEventListener('submit',e=>{const id=e.target.getAttribute('id');if(!['family-login','family-join'].includes(id))return;e.preventDefault();const fd=new FormData(e.target);if(id==='family-join'){action(()=>FamilySync.join(fd.get('code')));return}if(sending||Date.now()<nextAt)return;sending=true;cooldown();action(async()=>{try{await FamilySync.login(fd.get('email'))}finally{sending=false;loginButton()}})});
 setInterval(loginButton,1000);window.addEventListener('storage',e=>{if(e.key===cooldownKey){nextAt=Number(e.newValue)||0;loginButton()}});
 document.addEventListener('click',e=>{const a=e.target.closest('[data-family]')?.dataset.family;if(!a)return;action(()=>{if(a==='sync')return FamilySync.cycle();if(a==='out')return FamilySync.signout();if(a==='create')return FamilySync.create();if(a==='import'&&confirm('להעלות לטיול הפרטי את ההוצאות, התקציב, הסימונים והכרטיסים שנשמרו כאן לפני ההתחברות? הגיבוי המקומי הישן יישאר.'))return FamilySync.importLegacy()})});
 draw({message:'התחברו כדי לפתוח את התיק המשפחתי'});loginButton();FamilySync.start().catch(e=>document.querySelector('#family-status').textContent=errorMessage(e));
})();
