(()=>{
 const panel=document.createElement('section');panel.className='family-panel';panel.setAttribute('aria-label','סנכרון משפחתי');panel.innerHTML='<details><summary>🔒 התיק המשפחתי <span id="family-status" role="status">כניסה וסנכרון</span></summary><div id="family-controls"></div></details>';
 document.querySelector('#trip-overview').after(panel);let current='',state={};
 const safe=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function draw(s){state=s;document.querySelector('#family-status').textContent=s.message;const key=JSON.stringify([s.email,s.trip,s.active]);if(key===current)return;current=key;
  document.querySelector('#family-controls').innerHTML=!s.email?`<p>הכרטיסים, ההוצאות והסימונים משותפים רק לחשבונות שאושרו לטיול.</p><form id="family-login"><label>כתובת אימייל<input name="email" type="email" autocomplete="email" required dir="ltr"></label><button class="primarybutton">שליחת קישור כניסה</button></form>`:
   `<p>מחובר/ת: <bdi>${safe(s.email)}</bdi></p>`+(s.active?`<p>${safe(s.trip.name)} · קוד הצטרפות: <bdi><strong>${safe(s.trip.join_code)}</strong></bdi></p><p class="source">הקוד עובד רק עבור אימייל שאושר מראש. קבצים שכבר הורדתם למכשיר נשארים בשליטתכם.</p><div class="actions"><button class="softbutton" data-family="sync">סנכרון עכשיו</button><button class="softbutton" data-family="import">העברת הנתונים הישנים ממכשיר זה</button></div>`:`<p>יצירת טיול והצטרפות זמינות רק לחשבונות שאושרו במסד הנתונים.</p><button class="softbutton" data-family="create">יצירת הטיול שלנו</button><form id="family-join"><label>קוד הצטרפות<input name="code" required minlength="8" maxlength="8" dir="ltr"></label><button class="softbutton">הצטרפות</button></form>`)+`<button class="textbutton" data-family="out">יציאה וניקוי העותק הפרטי במכשיר</button>`;
 }
 window.addEventListener('tatry-sync-status',e=>draw(e.detail));
 async function action(fn){try{await fn()}catch(e){document.querySelector('#family-status').textContent='לא הושלם: '+e.message}}
 document.addEventListener('submit',e=>{if(!['family-login','family-join'].includes(e.target.getAttribute('id')))return;e.preventDefault();const form=e.target,fd=new FormData(form);action(()=>form.id==='family-login'?FamilySync.login(fd.get('email')):FamilySync.join(fd.get('code')))});
 document.addEventListener('click',e=>{const a=e.target.closest('[data-family]')?.dataset.family;if(!a)return;action(()=>{if(a==='sync')return FamilySync.cycle();if(a==='out')return FamilySync.signout();if(a==='create')return FamilySync.create();if(a==='import'&&confirm('להעלות לטיול הפרטי את ההוצאות, התקציב, הסימונים והכרטיסים שנשמרו כאן לפני ההתחברות? הגיבוי המקומי הישן יישאר.'))return FamilySync.importLegacy()})});
 draw({message:'התחברו כדי לפתוח את התיק המשפחתי'});FamilySync.start().catch(e=>document.querySelector('#family-status').textContent=e.message);
})();
