const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),{parseHTML}=require('linkedom'),path=require('path');
const root=path.join(__dirname,'..'),{document,MutationObserver,CustomEvent}=parseHTML(fs.readFileSync(path.join(root,'index.html'),'utf8'));
const saved=new Map(),events={};const c={document,MutationObserver,CustomEvent,NodeFilter:{SHOW_ELEMENT:1,SHOW_TEXT:4},console,Date,Intl,Set,Map,WeakMap,URL,crypto:require('crypto').webcrypto,navigator:{},location:{protocol:"https:"},setTimeout,clearTimeout,localStorage:{getItem:k=>saved.get(k)||null,setItem:(k,v)=>saved.set(k,v)},addEventListener:(n,f)=>(events[n]??=[]).push(f),dispatchEvent:e=>(events[e.type]||[]).forEach(f=>f(e)),TripTools:{isReady:()=>false,getReservations:()=>[],paintSaveStatus(){},init(){},fileCount:()=>0}};c.window=c;vm.createContext(c);
for(const f of ['i18n-dictionary.js','i18n.js','offline.js','data.js','place-photos.js','app.js','day-hub.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8').replace('\nrender();','\n'),c);
const missing=new Set();function inspect(){c.TripI18n.refresh();const walker=document.createTreeWalker(document.documentElement,4);let n;while(n=walker.nextNode()){if(!n.parentElement.closest('script,style,[translate="no"]')&&/[א-ת]/.test(n.nodeValue))missing.add(n.nodeValue.trim())}}
c.TripI18n.setLanguage('en');assert.equal(document.documentElement.lang,'en');assert.equal(document.documentElement.dir,'ltr');assert.equal(saved.get('tatry-language'),'en');
for(let day=0;day<10;day++){vm.runInContext(`day=${day};view='days';dayView()`,c);inspect()}
c.L={map:()=>({setView(){return this},fitBounds(){},remove(){}}),layerGroup:()=>({addTo(){return this},clearLayers(){}}),circleMarker:()=>({addTo(){return this},bindPopup(){return this},on(){},getElement:()=>document.createElement('path')}),tileLayer:()=>({addTo(){}})};vm.runInContext(fs.readFileSync(path.join(root,'map.js'),'utf8'),c);vm.runInContext('view="map";TripMap.show()',c);inspect();
for(const fn of ['placesView','bookingsView','visitsView','prepView','auditView','offlineView']){vm.runInContext(fn+'()',c);inspect()}
vm.runInContext('placesView()',c);c.TripI18n.refresh();const options=[...document.querySelectorAll('#kind option')];assert(options.some(o=>o.value==='אוכל'&&o.textContent==='Food')); assert(options.some(o=>o.value==='all'));
vm.runInContext("query='Waterfalls';updateResults()",c);c.TripI18n.refresh();assert(document.querySelector('#results').textContent.includes('Waterfalls'));
const input=document.querySelector('#search');input.value='unfinished text';c.TripI18n.setLanguage('he');assert.equal(input.value,'unfinished text');assert.equal(document.documentElement.dir,'rtl');assert(document.querySelector('.mainnav').textContent.includes('המסלול שלנו'));c.TripI18n.setLanguage('en');assert.equal(input.value,'unfinished text');assert(document.querySelector('.mainnav').textContent.includes('Our itinerary'));
const privateNode=document.createElement('p');privateNode.setAttribute('translate','no');privateNode.textContent='המלון';document.body.append(privateNode);c.TripI18n.refresh();assert.equal(privateNode.textContent,'המלון');
console.log('Untranslated public strings:',JSON.stringify([...missing],null,2));assert.equal(missing.size,0);console.log('PASS: 10 days + public views, language persistence, LTR/RTL, English search, unchanged option values, unsaved inputs and user text');
