const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),{parseHTML}=require('linkedom'),path=require('path');const root=fs.existsSync(path.join(__dirname,'../dist/data.js'))?path.join(__dirname,'../dist'):path.join(__dirname,'..');
const {document,Event}=parseHTML(fs.readFileSync(path.join(root,'index.html'),'utf8'));const events={};let ready=false,allMarkers=[],zoom=0;
const c={document,console,Date,Intl,Set,Map,URL,Event,crypto:require('crypto').webcrypto,navigator:{},setTimeout,clearTimeout,addEventListener:(n,f)=>(events[n]??=[]).push(f),TripTools:{isReady:()=>ready,getReservations:()=>ready?[{place:'bob',status:'booked',date:'2027-08-14',time:'10:30',reference:'PRIVATE-TEST'}]:[],fileCount:()=>0,paintSaveStatus(){},itemStatus:()=>'<div>saved</div>'}};c.window=c;vm.createContext(c);for(const f of ['data.js','place-photos.js','app.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8').replace('\nrender();','\n'),c);
vm.runInContext(fs.readFileSync(path.join(root,'day-hub.js'),'utf8'),c);
for(let day=0;day<10;day++){vm.runInContext(`day=${day};dayView()`,c);assert(document.querySelector('#hub-place'));assert.equal(document.querySelector('#reservation-form'),null);assert(!document.body.textContent.includes('PRIVATE-TEST'));const ids=[...document.querySelectorAll('[data-visit]')].map(e=>e.dataset.visit);assert.equal(ids.length,new Set(ids).size);}
ready=true;vm.runInContext('day=5;dayView()',c);assert(document.querySelector('#reservation-form'));assert(document.querySelector('#hub-place option[value="famosa"]'));assert.equal(document.querySelector('[name="reference"]').getAttribute('value'),'PRIVATE-TEST');
ready=false;(events['tatry-tools-updated']||[]).forEach(f=>f());assert.equal(document.querySelector('#reservation-form'),null);assert(!document.body.innerHTML.includes('PRIVATE-TEST'));
const ctx=vm.runInContext('({places:PLACES,photos:PLACE_PHOTOS})',c);assert.equal(ctx.places.length,43);for(const p of ctx.places){assert(p.photo,p.id);assert(fs.existsSync(path.join(root,p.photo.src)),p.id)}
c.L={map:()=>({setView(_,z){zoom=z;return this},getZoom:()=>zoom,fitBounds(){},remove(){}}),layerGroup:()=>({addTo(){return this},clearLayers(){}}),circleMarker:coords=>{const el=document.createElement('path'),m={coords,addTo(){allMarkers.push(this);return this},bindPopup(p){this.popup=p;return this},on(n,f){this[n]=f;return this},getElement:()=>el,setStyle(){},setRadius(){},bringToFront(){},openPopup(){},getLatLng:()=>coords};return m},tileLayer:()=>({addTo(){}})};
vm.runInContext(fs.readFileSync(path.join(root,'map.js'),'utf8'),c);vm.runInContext('view="map";TripMap.show()',c);assert.equal(document.querySelectorAll('[data-map-row]').length,43);assert(allMarkers.length<43,'shared sites should use a grouped marker');assert(document.body.textContent.includes('Priehyba'));const row=document.querySelector('[data-map-select="bachslide"]');document.querySelector('#trip-map').scrollIntoView=()=>{};document.querySelector('#map-list').onclick({target:row});assert.equal(document.querySelector('[data-map-row="bachslide"]').classList.contains('map-selected'),true);assert.equal(zoom,16);
console.log('PASS: 10 day overviews, private booking lock, distinct activity checks, 43 photo records, grouped map selection at zoom 16');
